title: Rdv-thé
remote_theme: oisiflorus/maquillage-danslajungle

defaults:
  - scope:
      path: ""
    values:
      layout: location

collections:
  vichy:
    output: true

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-titles-from-headings
